
import signup from "../support/signuppage"
const DataSignup = require ('../fixtures/datasignup.json')

const signupUsername = `cy${Math.random().toString().slice(2, 8)}`
describe('Sign Up', () => {
  const SignupPage = new signup()
  beforeEach(()=>{
    // random username 
    const random = `cy${Math.random().toString().slice(2, 8)}`
    cy.wrap(random).as('username')
    cy.wrap(signupUsername).as('signupUsername')
    cy.visit('/')
  })
  
  it('success register', function () {
    cy.get(SignupPage.signupbutton).click()
    cy.get(SignupPage.firstname).type(DataSignup.firstname)
    cy.get(SignupPage.surname).type(DataSignup.surname)
    cy.get(SignupPage.e_post).type(DataSignup.e_post)
    cy.get(SignupPage.mobile).type(DataSignup.mobile)
    cy.get(SignupPage.username).type(this.signupUsername)
    cy.get(SignupPage.password).type(DataSignup.password)
    cy.get(SignupPage.confirmpassword).type(DataSignup.confirmpassword)
    cy.get(SignupPage.submitbutton).click()
    cy.get(SignupPage.success_signup)
    .contains(SignupPage.success_validation_message).should('be.visible')
  })
  it('empty all field', function () {
    cy.get(SignupPage.signupbutton).click()
    cy.get(SignupPage.firstname)
    cy.get(SignupPage.surname)
    cy.get(SignupPage.e_post)
    cy.get(SignupPage.mobile)
    cy.get(SignupPage.username)
    cy.get(SignupPage.password)
    cy.get(SignupPage.confirmpassword)
    cy.get(SignupPage.submitbutton).click()
    cy.get(SignupPage.firstname_validation_error)
    .contains(SignupPage.firstname_validation_error_message).should('be.visible')
    cy.get(SignupPage.surname_validation_error)
    .contains(SignupPage.surname_validation_error_message).should('be.visible')
    cy.get(SignupPage.username_validation_error)
    .contains(SignupPage.username_validation_error_message).should('be.visible')
    cy.get(SignupPage.password_validation_error)
    .contains(SignupPage.password_validation_error_message).should('be.visible')
  })
  it('empty first name', function () {
    cy.get(SignupPage.signupbutton).click()
    cy.get(SignupPage.firstname)
    cy.get(SignupPage.surname).type(DataSignup.surname)
    cy.get(SignupPage.e_post).type(DataSignup.e_post)
    cy.get(SignupPage.mobile).type(DataSignup.mobile)
    cy.get(SignupPage.username).type(DataSignup.username)
    cy.get(SignupPage.password).type(DataSignup.password)
    cy.get(SignupPage.confirmpassword).type(DataSignup.confirmpassword)
    cy.get(SignupPage.submitbutton).click()
    cy.get(SignupPage.firstname_validation_error)
    .contains(SignupPage.firstname_validation_error_message).should('be.visible')
  })
  it('empty surname', function () {
    cy.get(SignupPage.signupbutton).click()
    cy.get(SignupPage.firstname).type(DataSignup.firstname)
    cy.get(SignupPage.surname)
    cy.get(SignupPage.e_post).type(DataSignup.e_post)
    cy.get(SignupPage.mobile).type(DataSignup.mobile)
    cy.get(SignupPage.username).type(this.username)
    cy.get(SignupPage.password).type(DataSignup.password)
    cy.get(SignupPage.confirmpassword).type(DataSignup.confirmpassword)
    cy.get(SignupPage.submitbutton).click()
    cy.get(SignupPage.surname_validation_error)
    .contains(SignupPage.surname_validation_error_message).should('be.visible')
  })
  it('empty e-post', function () {
    cy.get(SignupPage.signupbutton).click()
    cy.get(SignupPage.firstname).type(DataSignup.firstname)
    cy.get(SignupPage.surname).type(DataSignup.surname)
    cy.get(SignupPage.e_post)
    cy.get(SignupPage.mobile).type(DataSignup.mobile)
    cy.get(SignupPage.username).type(this.username)
    cy.get(SignupPage.password).type(DataSignup.password)
    cy.get(SignupPage.confirmpassword).type(DataSignup.confirmpassword)
    cy.get(SignupPage.submitbutton).click()
    cy.get(SignupPage.success_signup)
    .contains(SignupPage.success_validation_message).should('be.visible')
  })
  it('empty mobile', function () {
    cy.get(SignupPage.signupbutton).click()
    cy.get(SignupPage.firstname).type(DataSignup.firstname)
    cy.get(SignupPage.surname).type(DataSignup.surname)
    cy.get(SignupPage.e_post).type(DataSignup.e_post)
    cy.get(SignupPage.mobile)
    cy.get(SignupPage.username).type(this.username)
    cy.get(SignupPage.password).type(DataSignup.password)
    cy.get(SignupPage.confirmpassword).type(DataSignup.confirmpassword)
    cy.get(SignupPage.submitbutton).click()
    cy.get(SignupPage.success_signup)
    .contains(SignupPage.success_validation_message).should('be.visible')
  })
  it('empty username', function () {
    cy.get(SignupPage.signupbutton).click()
    cy.get(SignupPage.firstname).type(DataSignup.firstname)
    cy.get(SignupPage.surname).type(DataSignup.surname)
    cy.get(SignupPage.e_post).type(DataSignup.e_post)
    cy.get(SignupPage.mobile).type(DataSignup.mobile)
    cy.get(SignupPage.username)
    cy.get(SignupPage.password).type(DataSignup.password)
    cy.get(SignupPage.confirmpassword).type(DataSignup.confirmpassword)
    cy.get(SignupPage.submitbutton).click()
    cy.get(SignupPage.username_validation_error)
    .contains(SignupPage.username_validation_error_message).should('be.visible')
  })
  it('empty password', function () {
    cy.get(SignupPage.signupbutton).click()
    cy.get(SignupPage.firstname).type(DataSignup.firstname)
    cy.get(SignupPage.surname).type(DataSignup.surname)
    cy.get(SignupPage.e_post).type(DataSignup.e_post)
    cy.get(SignupPage.mobile).type(DataSignup.mobile)
    cy.get(SignupPage.username).type(DataSignup.username)
    cy.get(SignupPage.password)
    cy.get(SignupPage.confirmpassword)
    cy.get(SignupPage.submitbutton).click()
    cy.get(SignupPage.password_validation_error)
    .contains(SignupPage.password_validation_error_message).should('be.visible')
  })
  it('empty confirm password', function () {
    cy.get(SignupPage.signupbutton).click()
    cy.get(SignupPage.firstname).type(DataSignup.firstname)
    cy.get(SignupPage.surname).type(DataSignup.surname)
    cy.get(SignupPage.e_post).type(DataSignup.e_post)
    cy.get(SignupPage.mobile).type(DataSignup.mobile)
    cy.get(SignupPage.username).type(DataSignup.username)
    cy.get(SignupPage.password).type(DataSignup.password)
    cy.get(SignupPage.confirmpassword)
    cy.get(SignupPage.submitbutton).click()
    cy.get(SignupPage.confirmpassword_validation_error)
    .contains(SignupPage.confirmpassword_validation_error_message).should('be.visible')
  })
  it('password confirmation does not match password', function () {
    cy.get(SignupPage.signupbutton).click()
    cy.get(SignupPage.firstname).type(DataSignup.firstname)
    cy.get(SignupPage.surname).type(DataSignup.surname)
    cy.get(SignupPage.e_post).type(DataSignup.e_post)
    cy.get(SignupPage.mobile).type(DataSignup.mobile)
    cy.get(SignupPage.username).type(this.username)
    cy.get(SignupPage.password).type(DataSignup.password)
    cy.get(SignupPage.confirmpassword)
    cy.get(SignupPage.submitbutton).click()
    cy.get(SignupPage.confirmpassword_validation_error)
    .contains(SignupPage.confirmpassword_validation_error_message).should('be.visible')
  })
  it('sign up using an existing username', function () {
    cy.get(SignupPage.signupbutton).click()
    cy.get(SignupPage.firstname).type(DataSignup.firstname)
    cy.get(SignupPage.surname).type(DataSignup.surname)
    cy.get(SignupPage.e_post).type(DataSignup.e_post)
    cy.get(SignupPage.mobile).type(DataSignup.mobile)
    cy.get(SignupPage.username).type(this.signupUsername)
    cy.get(SignupPage.password).type(DataSignup.password)
    cy.get(SignupPage.confirmpassword).type(DataSignup.confirmpassword)
    cy.get(SignupPage.submitbutton).click()
    cy.get(SignupPage.username_exist_validation)
    .contains(SignupPage.username_exist_validation_message).should('be.visible')
  })
})